### ISSUE TITLE
Add msg.sender and dollar value to TipMessage event

### ISSUE THREAD

**Issue by idrisssystem** [idriss-crypto/contracts#1]
**Conract**
[Tipping](https://github.com/idriss-crypto/contracts/blob/main/tipping.sol)

**Is your feature request related to a problem? Please describe.**
When building a subsciption page tracking incoming tips, it is useful to have all relevant information available in the event receipt. Currently, the sender of a transaction and the amount in $ can only be determined after calling 
`await web3.eth.getTransaction(transactionHash)` and using the token contract address.

**Describe the solution you'd like**
Instead of using `emit TipMessage(recipient_, message_, msg.value);` or `emit TipMessage(recipient_, message_, amount_);`, I suggest using `emit TipMessage(recipient_, message_, msg.sender, val_);` in both _sendTo( ... )_ and _sendTokenTo( ... )_, which both need an additional input variable _val__ denoting the current $ value of the asset used to tip.

**Describe alternatives you've considered**
Instead of adding _val__ as an additional input variable, the asset contract address (or dummy value for native token) could be used. This requires additional calculations on the frontend, but could save complexity for on-chain actions.

**Comment by abdulqgg** [comment]
Is msg.value and amount_ the same as _val?

**Comment by idrisssystem** [comment]
The dollar value is not used in the contract yet, it would have to be an additional input to the respective tipping function. There are really two options that I see:

1. add dollar value as additional int input to sendTo(...) and sendTokenTo(...) and then pass it to the event TipMessage(). The last two digits would be decimals.
2. pass tokenContractAddress_ to the event TipMessage(). In the case of sendTo(), we could pass the contract address as a default. 

Any suggestions? 😊

**Comment by abdulqgg** [comment]
Ok sounds good, ive added a new uint256 variable called val to event TipMesaage and added it as an additional input to both sendTo and sendTokenTo functions. 
Check updated PR #4

**Comment by lennardevertz** [comment]
did you make any comparison of gas fees between the two options? If not I'll do it after I am back from EthCC.

**Comment by abdulqgg** [comment]
I did not, feel free to do so.

**Comment by lennardevertz** [comment]
Sorry for the late response. A few simple tests show that the additional input variable val_ is less efficient than just passing the contract address of the asset (or address(0) for native coins) to the event TipMessage. I will adjust it and close this.
