### ISSUE TITLE
Contract is too much Gas Costly

### ISSUE THREAD

**Issue by TradMod** [idriss-crypto/contracts#2]
**Is your feature request related to a problem? Please describe.**
 Not a bug but can be a big problem. As the tipping.sol includes so many `require` statements with a err message, it will be too much gas costly. As it stores a full length of string

**Describe the solution you'd like**
 A simple solution would be to use `Custom Errors` (with modifiers)

**Describe alternatives you've considered**
I think using Revert & Errors will be the best solution IA

**Additional context**
https://ethereum.stackexchange.com/questions/101782/requirecondition-message-vs-revert-with-a-custom-error-which-is-better-a

**Comment by TradMod** [comment]
I just made the Pull request with the solution and more gas optimized contract :)
Thanks

**Comment by idrisssystem** [comment]
Hey @DevABDee !
Welcome, and thank you for taking the initiative. Great input! I will go through your PR #3 today.
